{{- if not .Values.backend.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: coffee-api-secret
type: Opaque
data:
  COFFEE_API_KEY: {{ .Values.backend.secret.apiKey | b64enc }}
{{- end }}
