apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          envFrom:
            - secretRef:
                name: backend-secret
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: {{ default .Values.mongodb.secret.existingSecret "mongodb-secret" }}
                  key: MONGO_URI
