apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          env:
            - name: MONGO_URI
              value: {{ .Values.backend.env.MONGO_URI  }}
            - name: COFFEE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: coffee-api-secret
                  key: COFFEE_API_KEY
