{{- if not .Values.backend.secret.existingSecret }}

{{- $apiKey := "" }}
{{- if .Values.backend.secret.apiKey }}
  {{- $apiKey = .Values.backend.secret.apiKey }}
{{- else -}}
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace "backend-secret") }}
  {{- if $secret }}
    {{- $apiKey = index $secret.data "API_KEY" | b64dec }}
  {{- else}}
    {{- $apiKey = (randAlpha 16) }}
  {{- end }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  COFFEE_API_KEY: {{ $apiKey | b64enc }}
{{- end }}
