apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: mongodb
