{{- if not .Values.mongodb.secret.existingSecret }}

{{- $rootPasswordValue := "" }}
{{- if .Values.mongodb.secret.rootPassword }}
  {{- $rootPasswordValue = .Values.mongodb.secret.rootPassword }}
{{- else -}}
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace "mongodb-secret") }}
  {{- if $secret }}
    {{- $rootPasswordValue = index $secret.data "MONGO_INITDB_ROOT_PASSWORD" | b64dec }}
  {{- else}}
    {{- $rootPasswordValue = (randAlpha 16) }}
  {{- end }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  MONGO_URI: {{ printf "mongodb://%s:%s@mongodb:27017/coffee-counter?authSource=admin" .Values.mongodb.secret.rootUser $rootPasswordValue | b64enc | quote }}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.secret.rootUser | b64enc | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ $rootPasswordValue | b64enc | quote }}
{{- end}}
