mongodb:
  replicas: 1
  secret:
    existingSecret: '' # specify to use an existing secret
    rootUser: admin
    rootPassword: '' # if unspecified, will generate a random password
  persistence:
    storageClass: "-"
    existingClaim: ""
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi

imagePullSecrets:
  - name: registry-vs

backend:
  image: registry.uni-kassel.dev/coffee-counter/backend:latest
  replicas: 2
  secret:
    existingSecret: '' # specify to use an existing secret
    apiKey: '' # if blank, will generate a random key

frontend:
  image: registry.uni-kassel.dev/coffee-counter/frontend:latest
  replicas: 2

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
  className: nginx
  host: coffee.uni-kassel.dev
  tls:
    - secretName: coffee-cert
      hosts:
        - coffee.uni-kassel.dev
