mongodb:
  secret:
    existingSecret: 'mongodb-secret' # specify to use an existing secret
  backup:
    enabled: true
    # https://github.com/ds-ukassel/backup-mongodb-s3
    image: registry.uni-kassel.dev/backup/mongodb-s3
    schedule: "0 2 * * *" # every day at 2 am
    timeZone: Europe/Berlin
    # secret requires keys requires minio-uri (http(s)://accesskey:secretkey@hostname:port)
    existingSecret: 'backup-minio-secret'
    bucket: 'coffee-backups'
    # see https://github.com/ds-ukassel/backup-mongodb-s3?tab=readme-ov-file#configuration -> RETENTION_PERIOD
    # and https://min.io/docs/minio/linux/reference/minio-mc/mc-rm.html#mc.rm.-older-than
    keep: 14d

imagePullSecrets:
  - name: registry-vs

backend:
  image: registry.uni-kassel.dev/coffee-counter/backend:latest
  imagePullPolicy: Always
  replicas: 2
  secret:
    existingSecret: '' # specify to use an existing secret
    apiKey: '' # if blank, will generate a random key
    coffeePrice: 0.30

frontend:
  image: registry.uni-kassel.dev/coffee-counter/frontend:latest
  imagePullPolicy: Always
  replicas: 2

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  className: nginx
  host: coffee.uni-kassel.dev
  tls:
    - secretName: coffee-cert
      hosts:
        - coffee.uni-kassel.dev
