name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install PNPM
        run: npm install -g pnpm
      - name: Cache PNPM Store
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
            /.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('frontend/pnpm-lock.yaml') }}
          restore-keys: pnpm-${{ runner.os }}-
      - name: Install packages
        run: pnpm install
      - name: Build Angular
        run: pnpm build
      - name: Build the Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          image_name: coffee-counter/frontend
          image_tag: latest
          context: frontend/
      - name: Deploy to Rancher
        uses: sekassel-research/actions-rancher-update@2.0.2
        with:
          rancher_url: ${{ secrets.RANCHER_URL }}
          rancher_token: ${{ secrets.RANCHER_TOKEN }}
          cluster_id: ${{ secrets.RANCHER_CLUSTER }}
          project_id: ${{ secrets.RANCHER_PROJECT }}
          namespace: coffee-counter
          deployment: frontend
          docker_image: ${{ secrets.DOCKER_REGISTRY }}/coffee-counter/frontend:latest
  service:
    name: Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Docker Image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          image_name: coffee-counter/service
          image_tag: latest
          context: service/
      - name: Deploy to Rancher
        uses: sekassel-research/actions-rancher-update@2.0.2
        with:
          rancher_url: ${{ secrets.RANCHER_URL }}
          rancher_token: ${{ secrets.RANCHER_TOKEN }}
          cluster_id: ${{ secrets.RANCHER_CLUSTER }}
          project_id: ${{ secrets.RANCHER_PROJECT }}
          namespace: coffee-counter
          deployment: service
          docker_image: ${{ secrets.DOCKER_REGISTRY }}/coffee-counter/service:latest
