name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'service/**'
      - '.github/workflows/deploy-backend.yaml'

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: service/
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/coffee-counter/backend
          cache-to: type=gha,mode=max
          cache-from: type=gha
      - name: Deploy to Rancher
        uses: sekassel-research/actions-rancher-update@v4.0.2
        with:
          rancher_url: ${{ secrets.RANCHER_URL }}
          rancher_token: ${{ secrets.RANCHER_TOKEN }}
          cluster_id: ${{ secrets.RANCHER_CLUSTER }}
          namespace: coffee-counter
          kind: deployment
          workload: backend
          docker_image: ${{ secrets.DOCKER_REGISTRY }}/coffee-counter/backend
