name: PR Preview Deploy

on:
  pull_request:

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install pnpm
        id: pnpm-install
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install packages
        run: pnpm install
      - name: Build Angular
        run: pnpm build --configuration production --base-href /coffee-counter-ultimate/pr/${{ github.pull_request.number }}/
      - name: Publish to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/frontend/
          destination_dir: pr/{{ github.pull_request.number }}/
      - name: Add PR Comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.pull_request.number }}
          body: |
            Deployed to https://sekassel-research.github.io/pr/${{ github.pull_request.number }}/
          reactions: '+1'
